name: dailyremember
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.3.3
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.1
  audioplayers: ^5.2.0
  record: ^5.0.1
  audio_waveforms: ^1.0.4
  iconly: ^1.0.1
  flutter_snake_navigationbar: ^0.6.1
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  d_chart: ^2.6.2
  flutter_slidable_panel: ^1.1.3
  flutter_speed_dial: ^7.0.0
  circular_countdown_timer: ^0.2.3
  simple_circular_progress_bar: ^1.0.2
  avatar_glow:
    git:
      url: https://github.com/apgapg/avatar_glow
      ref: master
  speech_to_text: ^6.4.0
  substring_highlight: ^1.0.33
  local_auth: ^2.1.7
  ffmpeg_kit_flutter: ^6.0.3
  language_tool: ^2.2.0
  languagetool_textfield: ^0.0.5
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/


