name: dailyremember
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.3.3
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.1
  audioplayers: ^5.2.0
  record: ^5.0.1
  audio_waveforms: ^1.0.4
  iconly: ^1.0.1
  flutter_snake_navigationbar: ^0.6.1
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  d_chart: ^2.6.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/json/

